export const PERTH_SUBURBS = [
  { name: "Applecross", slug: "applecross", postCode: "6153" },
  { name: "Armadale", slug: "armadale", postCode: "6112" },
  { name: "Atwell", slug: "atwell", postCode: "6164" },
  { name: "Aubin Grove", slug: "aubin-grove", postCode: "6164" },
  { name: "Balcatta", slug: "balcatta", postCode: "6021" },
  { name: "Baldivis", slug: "baldivis", postCode: "6171" },
  { name: "Bassendean", slug: "bassendean", postCode: "6054" },
  { name: "Bayswater", slug: "bayswater", postCode: "6053" },
  { name: "Beechboro", slug: "beechboro", postCode: "6063" },
  { name: "Beeliar", slug: "beeliar", postCode: "6164" },
  { name: "Belmont", slug: "belmont", postCode: "6104" },
  { name: "Bentley", slug: "bentley", postCode: "6102" },
  { name: "Bertram", slug: "bertram", postCode: "6167" },
  { name: "Bibra Lake", slug: "bibra-lake", postCode: "6163" },
  { name: "Bicton", slug: "bicton", postCode: "6157" },
  { name: "Bull Creek", slug: "bull-creek", postCode: "6149" },
  { name: "Butler", slug: "butler", postCode: "6036" },
  { name: "Byford", slug: "byford", postCode: "6122" },
  { name: "Canning Vale", slug: "canning-vale", postCode: "6155" },
  { name: "Cannington", slug: "cannington", postCode: "6107" },
  { name: "Carlisle", slug: "carlisle", postCode: "6101" },
  { name: "Churchlands", slug: "churchlands", postCode: "6018" },
  { name: "Claremont", slug: "claremont", postCode: "6010" },
  { name: "Clarkson", slug: "clarkson", postCode: "6030" },
  { name: "Cockburn", slug: "cockburn", postCode: "6166" },
  { name: "Cockburn Central", slug: "cockburn-central", postCode: "6164" },
  { name: "Como", slug: "como", postCode: "6152" },
  { name: "Cottesloe", slug: "cottesloe", postCode: "6011" },
  { name: "Currambine", slug: "currambine", postCode: "6028" },
  { name: "Dianella", slug: "dianella", postCode: "6059" },
  { name: "East Fremantle", slug: "east-fremantle", postCode: "6158" },
  { name: "East Perth", slug: "east-perth", postCode: "6004" },
  { name: "East Victoria Park", slug: "east-victoria-park", postCode: "6101" },
  { name: "Eglinton", slug: "eglinton", postCode: "6034" },
  { name: "Ellenbrook", slug: "ellenbrook", postCode: "6069" },
  { name: "Floreat", slug: "floreat", postCode: "6014" },
  { name: "Forrestfield", slug: "forrestfield", postCode: "6058" },
  { name: "Fremantle", slug: "fremantle", postCode: "6160" },
  { name: "Girrawheen", slug: "girrawheen", postCode: "6064" },
  { name: "Gosnells", slug: "gosnells", postCode: "6110" },
  { name: "Greenwood", slug: "greenwood", postCode: "6024" },
  { name: "Hamilton Hill", slug: "hamilton-hill", postCode: "6163" },
  { name: "Harrisdale", slug: "harrisdale", postCode: "6112" },
  { name: "Highgate", slug: "highgate", postCode: "6003" },
  { name: "Hillarys", slug: "hillarys", postCode: "6025" },
  { name: "Huntingdale", slug: "huntingdale", postCode: "6110" },
  { name: "Inglewood", slug: "inglewood", postCode: "6052" },
  { name: "Innaloo", slug: "innaloo", postCode: "6018" },
  { name: "Joondalup", slug: "joondalup", postCode: "6027" },
  { name: "Kalamunda", slug: "kalamunda", postCode: "6076" },
  { name: "Karrinyup", slug: "karrinyup", postCode: "6018" },
  { name: "Kelmscott", slug: "kelmscott", postCode: "6111" },
  { name: "Kenwick", slug: "kenwick", postCode: "6107" },
  { name: "Kingsley", slug: "kingsley", postCode: "6026" },
  { name: "Leederville", slug: "leederville", postCode: "6007" },
  { name: "Leeming", slug: "leeming", postCode: "6149" },
  { name: "Madeley", slug: "madeley", postCode: "6065" },
  { name: "Malaga", slug: "malaga", postCode: "6090" },
  { name: "Mandurah", slug: "mandurah", postCode: "6210" },
  { name: "Manning", slug: "manning", postCode: "6152" },
  { name: "Maylands", slug: "maylands", postCode: "6051" },
  { name: "Melville", slug: "melville", postCode: "6156" },
  { name: "Midland", slug: "midland", postCode: "6056" },
  { name: "Mindarie", slug: "mindarie", postCode: "6030" },
  { name: "Mirrabooka", slug: "mirrabooka", postCode: "6061" },
  { name: "Morley", slug: "morley", postCode: "6062" },
  { name: "Mosman Park", slug: "mosman-park", postCode: "6012" },
  { name: "Mount Hawthorn", slug: "mount-hawthorn", postCode: "6016" },
  { name: "Mount Lawley", slug: "mount-lawley", postCode: "6050" },
  { name: "Mount Pleasant", slug: "mount-pleasant", postCode: "6153" },
  { name: "Mundaring", slug: "mundaring", postCode: "6073" },
  { name: "Murdoch", slug: "murdoch", postCode: "6150" },
  { name: "Myaree", slug: "myaree", postCode: "6154" },
  { name: "Nedlands", slug: "nedlands", postCode: "6009" },
  { name: "North Fremantle", slug: "north-fremantle", postCode: "6159" },
  { name: "North Perth", slug: "north-perth", postCode: "6006" },
  { name: "Northbridge", slug: "northbridge", postCode: "6003" },
  { name: "Osborne Park", slug: "osborne-park", postCode: "6017" },
  { name: "Padbury", slug: "padbury", postCode: "6025" },
  { name: "Palmyra", slug: "palmyra", postCode: "6157" },
  { name: "Peppermint Grove", slug: "peppermint-grove", postCode: "6011" },
  { name: "Perth", slug: "perth", postCode: "6000" },
  { name: "Piara Waters", slug: "piara-waters", postCode: "6112" },
  { name: "Rivervale", slug: "rivervale", postCode: "6103" },
  { name: "Rockingham", slug: "rockingham", postCode: "6168" },
  { name: "Scarborough", slug: "scarborough", postCode: "6019" },
  { name: "Secret Harbour", slug: "secret-harbour", postCode: "6173" },
  { name: "Shenton Park", slug: "shenton-park", postCode: "6008" },
  { name: "South Lake", slug: "south-lake", postCode: "6164" },
  { name: "South Perth", slug: "south-perth", postCode: "6151" },
  { name: "Southern River", slug: "southern-river", postCode: "6110" },
  { name: "Spearwood", slug: "spearwood", postCode: "6163" },
  { name: "Stirling", slug: "stirling", postCode: "6021" },
  { name: "Subiaco", slug: "subiaco", postCode: "6008" },
  { name: "Success", slug: "success", postCode: "6164" },
  { name: "Swan View", slug: "swan-view", postCode: "6056" },
  { name: "Swanbourne", slug: "swanbourne", postCode: "6010" },
  { name: "Thornlie", slug: "thornlie", postCode: "6108" },
  { name: "Tuart Hill", slug: "tuart-hill", postCode: "6060" },
  { name: "Victoria Park", slug: "victoria-park", postCode: "6100" },
  { name: "Waikiki", slug: "waikiki", postCode: "6169" },
  { name: "Wanneroo", slug: "wanneroo", postCode: "6065" },
  { name: "Warwick", slug: "warwick", postCode: "6024" },
  { name: "Wembley", slug: "wembley", postCode: "6014" },
  { name: "West Leederville", slug: "west-leederville", postCode: "6007" },
  { name: "West Perth", slug: "west-perth", postCode: "6005" },
  { name: "Willetton", slug: "willetton", postCode: "6155" },
  { name: "Woodvale", slug: "woodvale", postCode: "6026" },
  { name: "Yangebup", slug: "yangebup", postCode: "6164" },
  { name: "Yokine", slug: "yokine", postCode: "6060" },
] as const;

export type PerthSuburb = (typeof PERTH_SUBURBS)[number];

export function findSuburb(slugOrPostCode: string): PerthSuburb | undefined {
  // Try exact slug match first
  const bySlug = PERTH_SUBURBS.find((s) => s.slug === slugOrPostCode);
  if (bySlug) return bySlug;
  // Try postcode match
  return PERTH_SUBURBS.find((s) => s.postCode === slugOrPostCode);
}

/** Find all suburbs matching a postcode */
export function findSuburbsByPostCode(postCode: string): PerthSuburb[] {
  return PERTH_SUBURBS.filter((s) => s.postCode === postCode);
}
