server {
    listen 80;
    server_name beauty.appilico.com.au;

    location = /googleeab34b015692a2b8.html {
        root /var/www/certbot;
        add_header Cache-Control "no-store";
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
